name: Build Workflow

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifact
          mv bundle/target/Adv*.jar artifact/

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: AdvancedBan
          path: artifact
