name: Unit tests

on:
  pull_request:
    branches: [ master, development ]
  push:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up OpenJDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
        distribution: microsoft

    - name: Test with Maven
      run: mvn -B test --file pom.xml
